services:
  nginx:
    build:
      context: .
    ports:
      - 3000:80
    volumes:
      - ./dist:/usr/share/nginx/html
      # - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
# docker compose -p react-nginx up -d
